### ISSUE TITLE
HU-001-TA-01 Crear página de inicio

### ISSUE THREAD

**Issue by MarcoPavez** [MarcoPavez/Dashboard-indicadores-economicos#6]
Objetivo de la tarea: Crear la página de inicio para el dashboard/panel de información

La página deberá contener:

- Un navbar con botones de redireccionamiento a:
     - Inicio 
     - Página de glosario
     - Inicio de sesión / Cierre de sesión
     - Luego de iniciar sesión, debe mostrar el perfil de la persona
- Un texto de bienvenida
- Una descripción del funcionamiento de la página
- Una sección que contenga:
     - Los indicadores a seleccionar
     - La fecha a seleccionar
- Una sección que despliegue la información del indicador y fecha seleccionados

**Comment by LucasA75** [comment]
Voy a hacer esto , te voy avisando que tal

**Comment by MarcoPavez** [comment]
Lo siento, olvidé agregar responsables
